name: Build and publish image for tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing tag to build and publish (e.g., v1.2.3)'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: $${ github.events.inputs.tag }

      - run: ./builder/build_container
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
