Base-Name: sdk
Repository: linux.elektrobit.com/ebcl
Base-Container: ubuntu:22.04
Version: v1.3.7
Layers:
  - layers/base
  - layers/pbuilder
  - layers/rust
  - layers/kiwi
  - layers/elbe
  - layers/appdev
  - layers/embdgen
  - layers/vscode
