#!/bin/bash

VERSION="v1.3.7"

if [ -z $RUNNER ]; then
    # docker or podman
    RUNNER="docker"
fi
echo "RUNNER: ${RUNNER}"

if [ -z $CONTAINER_NAME ]; then
    CONTAINER_NAME="ebcl_sdk"
fi
echo "CONTAINER_NAME: ${CONTAINER_NAME}"

lsmod | grep binfmt_misc
if [ $? -ne 0 ]; then
    echo "Trying to load binfmt kernel module for cross-builds ..."
    sudo modprobe binfmt_misc
fi

$RUNNER run --rm -it \
    --name $CONTAINER_NAME \
    -v ${HOME}/.ssh:/home/ebcl/.ssh:ro \
    -v /dev:/dev \
    --privileged \
    linux.elektrobit.com/ebcl/sdk:${VERSION}
