#!/bin/bash

set -e

cd $(dirname "${BASH_SOURCE[0]}")
echo "Current directory: $PWD"

GIT_ROOT=$(git rev-parse --show-toplevel)
VENV_DIR="${GIT_ROOT}/.venv"
VERSION=$(cat ${GIT_ROOT}/configuration/build_config.yaml | grep Version: | awk -F " " '{print $2}')

if [[ ! -d $VENV_DIR ]]; then
    echo "Preparing venv for the tests..."
    pushd .
    cd $GIT_ROOT
    python3 -m venv .venv
    popd
fi

source ${VENV_DIR}/bin/activate
pip install -r ${GIT_ROOT}/requirements.txt

echo "Running the tests for dev container ${VERSION}..."

robot -L TRACE *.robot
