FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \ 
 && apt-get install --no-install-recommends -y \
    build-essential \
    flex \
    bison \
    bc \
    libssl-dev \
    libncurses-dev \
    rsync \
    kmod \
    cpio \
    make

