name: Build and test image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt

      - run: env
      - run: ./builder/build_container
      - run: ./tests/run_tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-test-log
          path: tests/log.html
