name: Build and publish image for tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing tag to build and publish (e.g., v1.2.3)"
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.events.inputs.tag }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt

      - run: ./builder/build_container
      - run: ./tests/run_tests
      # - run: ./builder/publish_container
